# Archivo de configuración para LANRHandTracker
#
# Para una descripción completa de cada una de las opciones de configuracion de aparecen en este archivo, por favor
# revisar el archivo CONFIGURATION.md o https://github.com/geromt/LANRHandTracker
#

config:
  camera_index: 0
  port: 5052
  config_frame: false
  frame_height: 720
  frame_width: 1280
  display_video: true
  display_video_size: 1
  draw_hand: true
  static_mode: false
  max_hands: 2
  model_complexity: 1
  min_detection_confidence: 0.1
  min_tracking_confidence: 0.1

output:
  include_fps: false
  type: true
  include_height: false
  include_width: false
  flip_x: false
  flip_y: false
  lm_list: []
  include_box: false
  include_center: false
  coordinates: "pixel"
  round: 2
  print_data: true